---
<<<<<<< HEAD
title: "Lab 0002 - Global plastic waste"
<<<<<<< HEAD
<<<<<<< HEAD
author: "Team Name: DrewGoldstein, ShaneChesen, Sam Prior, Memito08, Dimitris Bardanis and DimitrisAgouridis"
=======
author: "Team Name: DrewGoldstein, ShaneChesen, Sam Prior, Memito08, Dimitris Bardanis and Dimitris Agouridis"
=======
=======
title: "Lab 002 - Global plastic waste"
>>>>>>> a1a9ce20c5570c7b504ca62c664f7294fc2b51b0
author: "6 MusketRs: DrewGoldstein, ShaneChesen, Sam Prior, Memito08, user5 and DimitrisAgouridis"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 2 (pair 1) write code to load File 1 data here:

file_1 <- read.csv("data/mismanaged-plastic-waste-per-capita.csv")

# Member 4 (pair 2) write code to load File 2 data here:

file_2 <- read.delim("data/per-capita-ocean-plastic-waste.txt",sep=";")

# Member 6 (pair 3) write code to load File 3 data here:

file_3 <- read.delim("data/UN_country_population.tsv",sep="\t")

# Member 1 (pair 1) write code to load File 4 data here:

file_4 <- read_xlsx("data/UN_country_region.xlsx")

```



```{r join-data, message = FALSE}
# Member 2 (pair 1) write code to create object 'plastic_data_all':

plastic_data_all <- file_1


# Member 4 (pair 2) write code to join your data to 'plastic_data_all':




# Member 6 (pair 3) write code to join your data to 'plastic_data_all':




# Member 1 (pair 1) write code to join your data to 'plastic_data_all':



```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'

plastic_data_all %>% head(n = 10)

```


## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1



```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2



```


### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3



```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
